[template]
cargo_generate_version = ">=0.17.4"
include = ["../Cargo.toml", "../build.rs", "../.gitignore"]

[hooks]
pre = ["pre-script.rhai"]
post = ["post-script.rhai"]

[placeholders.mcu]
type = "string"
prompt = "Which MCU to target?"
choices = ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s2", "esp32s3"]
default = "esp32"

[placeholders.advanced]
type = "bool"
prompt = "Configure advanced template options?"
default = false

[conditional.'advanced'.placeholders.alloc]
type = "bool"
prompt = "Enable allocations via the esp-alloc crate?"
default = false

[conditional.'advanced'.placeholders.wifi]
type    = "bool"
prompt  = "Enable WiFi/Bluetooth/ESP-NOW via the esp-wifi crate?"
default = false

[conditional.'advanced'.placeholders.devcontainer]
type = "bool"
prompt = "Configure project to use Dev Containers (VS Code and GitHub Codespaces)?"
default = false

[conditional.'advanced'.placeholders.wokwi]
type = "bool"
prompt = "Configure project to support Wokwi simulation with Wokwi VS Code extension?"
default = false

[conditional.'advanced'.placeholders.ci]
type = "bool"
prompt = "Add CI files for GitHub Action?"
default = false

[conditional.'devcontainer']
include = [
    "../.devcontainer/",
    "../.vscode/tasks.json",
    "../docs/",
    "../scripts/",
    "../.dockerignore",
]

[conditional.'ci']
include = ["../.github"]

[conditional.'wokwi']
include = ["../.vscode/launch.json", "../diagram.json", "../wokwi.toml"]

[conditional.'advanced']
include = [
    "../.devcontainer/",
    "../.vscode/",
    "../docs/",
    "../scripts/",
    "../.github",
    "../.dockerignore",
    "../diagram.json",
    "../wokwi.toml",
]
