print("");
print("============================================");
print("⚠️ This template is no longer supported. ⚠️");
print("============================================");
print("");
print("esp-template is no longer supported and we do not recommend using it.");
print("We suggest using esp-generate instead to get you started.");
print("For more information about esp-generate, visit https://github.com/esp-rs/esp-generate");
print("");